### ISSUE TITLE
php resque start提示错误

### ISSUE THREAD

**Issue by thinkdai** [xiao-xiangyeyu/thinkphp3.2.3-php-resque#1]
php resque start
运行以后提示找不到控制器
FILE: /www/wwwroot/collage.cn/Application/Runtime/common~runtime.php(1)
#0 /www/wwwroot/collage.cn/Application/Runtime/common~runtime.php(1): E('\xE6\x97\xA0\xE6\xB3\x95\xE5\x8A\xA0\xE8\xBD\xBD\xE6\x8E\xA7...')
#1 /www/wwwroot/collage.cn/Application/Runtime/common~runtime.php(1): Think\App::exec()
#2 /www/wwwroot/collage.cn/ThinkPHP/Library/Think/Think.class.php(120): Think\App::run()
#3 /www/wwwroot/collage.cn/ThinkPHP/ThinkPHP.php(97): Think\Think::start()
#4 /www/wwwroot/collage.cn/resque(16): require('/www/wwwroot/co...')

**Comment by thinkdai** [comment]
不好意思忘记上传控制器文件了！！
